add messages and ubuntu 14.04 to make nfs work

diff --git a/ec4docker b/ec4docker
--- a/ec4docker
+++ b/ec4docker
@@ -169,10 +169,16 @@ function terminate_cluster() {
                             echo "killing container $WNNAME"
                             $DOCKERCMD stop $WNNAME > /dev/null 2> /dev/null
                             $DOCKERCMD rm $WNNAME > /dev/null 2> /dev/null
+                            if [ $? -ne 0 ]; then
+                                echo "ERROR: failed to terminate $WNNAME"
+                            fi
                     done
                     echo "killing container $EC4DOCK_SERVERNAME"
                     $DOCKERCMD stop $EC4DOCK_SERVERNAME > /dev/null 2> /dev/null
                     $DOCKERCMD rm $EC4DOCK_SERVERNAME > /dev/null 2> /dev/null
+                    if [ $? -ne 0 ]; then
+                        echo "ERROR: failed to terminate $EC4DOCK_SERVERNAME"
+                    fi
             else
                     exit 1
             fi
