exposing SSH port of the frontend and license in files

diff --git a/wn/start-node b/wn/start-node
--- a/wn/start-node
+++ b/wn/start-node
@@ -1,11 +1,37 @@
 #!/bin/bash
-# Now execute the scripts in the conf.d folder
+#
+# EC4Docker - Elastic Cluster for Docker
+# https://github.com/grycap/ec4docker
+#
+# Copyright (C) GRyCAP - I3M - UPV 
+# Developed by Carlos A. caralla@upv.es
+#
+# Licensed under the Apache License, Version 2.0 (the "License");
+# you may not use this file except in compliance with the License.
+# You may obtain a copy of the License at
+#
+# http://www.apache.org/licenses/LICENSE-2.0
+#
+# Unless required by applicable law or agreed to in writing, software
+# distributed under the License is distributed on an "AS IS" BASIS,
+# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+# See the License for the specific language governing permissions and
+# limitations under the License.
+#
+
+# We just execute the executable scripts in the conf.d folder
 
 BASEDIR=$(dirname $0)
 if [ -d $BASEDIR/conf.d ]; then
     for scriptname in $BASEDIR/conf.d/*; do
-        echo $scriptname
-        [ -x $scriptname ] && $scriptname
+        if [ -x $scriptname ]; then
+            stdbuf -oL -eL $scriptname
+            if [ $? -eq 0 ]; then
+                echo -e "Execution of $scriptname [\e[32msucceeded\e[0m]"
+            else
+                echo -e "Execution of $scriptname [\e[31mfailed\e[0m]"
+            fi
+        fi
     done
 fi
 
